version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: "/.github/actions/install-concordia"
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: "/.github/actions/install-examples"
    schedule:
      interval: monthly

  - package-ecosystem: devcontainers
    directory: /.devcontainer
    schedule:
      interval: monthly
