name: pylint-concordia

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-concordia.yml'
      - '.pylintrc'
      - 'concordia/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-concordia.yml'
      - '.pylintrc'
      - 'concordia/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint Concordia
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Install Concordia
        uses: ./.github/actions/install-concordia

      - name: Run PyLint on Concordia
        run: pylint --errors-only concordia
