name: pylint-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'bin/convert_notebooks.sh'
      - 'concordia/**'
      - 'examples/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'bin/convert_notebooks.sh'
      - 'concordia/**'
      - 'examples/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint examples
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install examples
        uses: ./.github/actions/install-examples

      - name: Run PyLint on examples
        run: pylint --errors-only examples

      - name: Convert notebooks
        run: ./bin/convert_notebooks.sh notebooks

      - name: Run PyLint on notebooks
        run: pylint --errors-only notebooks
