name: pylint-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'concordia/**'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-examples/action.yml'
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/pylint-examples.yml'
      - '.pylintrc'
      - 'examples/**'
      - 'concordia/**'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint examples
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install examples
        uses: ./.github/actions/install-examples

      - name: Run PyLint on examples
        run: pylint --errors-only examples
