name: test-concordia

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install/action.yml'
      - '.github/workflows/test-concordia.yml'
      - '.pylintrc'
      - 'bin/install.sh'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install/action.yml'
      - '.github/workflows/test-concordia.yml'
      - '.pylintrc'
      - '.python-version'
      - 'bin/install.sh'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-concordia:
    name: Test Concordia
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Concordia
        uses: ./.github/actions/install

      - name: Test Concordia
        run: pytest concordia

      - name: Lint Concordia
        run: pylint --errors-only concordia

      - name: Typecheck Concordia
        run: pytype concordia
